# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: freefire.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'freefire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66reefire.proto\"B\n\x0bUintMessage\x12\r\n\x05value\x18\x01 \x01(\x04\x12\r\n\x05\x65xtra\x18\x02 \x01(\x04\x12\x15\n\roptionalField\x18\x03 \x01(\r\";\n\x08Getliked\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\r\n\x05liked\x18\x15 \x01(\x04\"\x1d\n\nextractjwt\x12\x0f\n\x07\x66ield_8\x18\x08 \x01(\t\"\x1b\n\x0b\x66uzzySearch\x12\x0c\n\x04name\x18\x01 \x01(\t\"_\n\x06Player\x12\x11\n\taccountId\x18\x01 \x01(\x04\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\r\x12\x11\n\tlastLogin\x18\x18 \x01(\r\"\"\n\x07Players\x12\x17\n\x06player\x18\x01 \x03(\x0b\x32\x07.Playerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'freefire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UINTMESSAGE']._serialized_start=18
  _globals['_UINTMESSAGE']._serialized_end=84
  _globals['_GETLIKED']._serialized_start=86
  _globals['_GETLIKED']._serialized_end=145
  _globals['_EXTRACTJWT']._serialized_start=147
  _globals['_EXTRACTJWT']._serialized_end=176
  _globals['_FUZZYSEARCH']._serialized_start=178
  _globals['_FUZZYSEARCH']._serialized_end=205
  _globals['_PLAYER']._serialized_start=207
  _globals['_PLAYER']._serialized_end=302
  _globals['_PLAYERS']._serialized_start=304
  _globals['_PLAYERS']._serialized_end=338
# @@protoc_insertion_point(module_scope)
